import type { Locale } from "./i18n";
import type { Film, FilmAnalysis, LocalizedText } from "./types";

// TMDB API anahtarı yokken sitenin boş görünmemesi için küçük bir demo katalog.
// Poster yolları TMDB'nin herkese açık görsel CDN'inden geliyor (anahtar gerektirmez).
// Anahtar girildiğinde bu liste yalnızca yedek olarak kalır.

interface DemoFilm extends Omit<Film, "overview" | "genres"> {
  overview: LocalizedText;
  genres: { tr: string[]; en: string[] };
}

const DEMO_FILMS_RAW: DemoFilm[] = [
  {
    tmdbId: 597,
    genreIds: [18, 10749],
    originalLanguage: "en",
    title: "Titanic",
    originalTitle: "Titanic",
    releaseYear: 1997,
    runtime: 194,
    posterPath: "/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    overview: {
      tr: "1912'de ilk seferine çıkan Titanic'te tanışan Jack ve Rose'un, sınıf farklarına ve yaklaşan felakete rağmen yeşeren aşkı.",
      en: "Jack and Rose meet aboard the Titanic on its 1912 maiden voyage; their love grows despite class differences and the looming disaster.",
    },
    genres: { tr: ["Dram", "Romantik"], en: ["Drama", "Romance"] },
    director: "James Cameron",
    cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane"],
    voteAverage: 7.9,
  },
  {
    tmdbId: 313369,
    genreIds: [35, 18, 10402, 10749],
    originalLanguage: "en",
    title: "La La Land",
    originalTitle: "La La Land",
    releaseYear: 2016,
    runtime: 128,
    posterPath: "/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    overview: {
      tr: "Los Angeles'ta hayallerinin peşinden koşan bir caz piyanisti ile oyuncu adayının müzikle örülü aşk hikâyesi.",
      en: "A jazz pianist and an aspiring actress chase their dreams in Los Angeles as their love story unfolds through music.",
    },
    genres: {
      tr: ["Müzikal", "Romantik", "Dram"],
      en: ["Musical", "Romance", "Drama"],
    },
    director: "Damien Chazelle",
    cast: ["Ryan Gosling", "Emma Stone"],
    voteAverage: 7.9,
  },
  {
    tmdbId: 603,
    genreIds: [28, 878],
    originalLanguage: "en",
    title: "The Matrix",
    originalTitle: "The Matrix",
    releaseYear: 1999,
    runtime: 136,
    posterPath: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    overview: {
      tr: "Gerçek sandığı dünyanın bir simülasyon olduğunu öğrenen Neo'nun, insanlığı makinelere karşı verilen savaşta uyanışı.",
      en: "Neo discovers the world he knows is a simulation and awakens to humanity's war against the machines.",
    },
    genres: { tr: ["Bilim Kurgu", "Aksiyon"], en: ["Science Fiction", "Action"] },
    director: "Lana & Lilly Wachowski",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    voteAverage: 8.2,
  },
  {
    tmdbId: 238,
    genreIds: [18, 80],
    originalLanguage: "en",
    title: "The Godfather",
    originalTitle: "The Godfather",
    releaseYear: 1972,
    runtime: 175,
    posterPath: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    overview: {
      tr: "Corleone ailesinin reisi Vito Corleone'nin gücünü ve isteksiz oğlu Michael'ın aile imparatorluğunu devralışını anlatan mafya destanı.",
      en: "The mafia saga of patriarch Vito Corleone's power and his reluctant son Michael's takeover of the family empire.",
    },
    genres: { tr: ["Suç", "Dram"], en: ["Crime", "Drama"] },
    director: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Al Pacino", "James Caan"],
    voteAverage: 8.7,
  },
  {
    tmdbId: 550,
    genreIds: [18, 53],
    originalLanguage: "en",
    title: "Fight Club",
    originalTitle: "Fight Club",
    releaseYear: 1999,
    runtime: 139,
    posterPath: "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    overview: {
      tr: "Uykusuzluk çeken bir ofis çalışanının, karizmatik sabun üreticisi Tyler Durden ile kurduğu yeraltı dövüş kulübünün kontrolden çıkışı.",
      en: "An insomniac office worker forms an underground fight club with charismatic soap maker Tyler Durden — and it spirals out of control.",
    },
    genres: { tr: ["Dram", "Gerilim"], en: ["Drama", "Thriller"] },
    director: "David Fincher",
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    voteAverage: 8.4,
  },
  {
    tmdbId: 157336,
    genreIds: [12, 18, 878],
    originalLanguage: "en",
    title: "Interstellar",
    originalTitle: "Interstellar",
    releaseYear: 2014,
    runtime: 169,
    posterPath: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    overview: {
      tr: "Dünya yaşanmaz hâle gelirken, insanlığa yeni bir yuva bulmak için solucan deliğinden geçen bir grup kâşifin yolculuğu.",
      en: "As Earth becomes uninhabitable, a team of explorers travels through a wormhole to find humanity a new home.",
    },
    genres: {
      tr: ["Bilim Kurgu", "Dram", "Macera"],
      en: ["Science Fiction", "Drama", "Adventure"],
    },
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    voteAverage: 8.4,
  },
  {
    tmdbId: 292431,
    genreIds: [18, 10749],
    originalLanguage: "en",
    title: "Love",
    originalTitle: "Love",
    releaseYear: 2015,
    runtime: 135,
    // Poster bilinçli olarak kapalı (afiş müstehcen); istenirse geri açılır:
    // "/yz6lmOmsmYuj6AOLG4LIwK5eJZF.jpg"
    posterPath: null,
    overview: {
      tr: "Gaspar Noé'den, bir ilişkinin tutkusunu ve çöküşünü son derece açık sahnelerle anlatan tartışmalı film.",
      en: "Gaspar Noé's controversial film depicting a relationship's passion and collapse through extremely explicit scenes.",
    },
    genres: { tr: ["Dram", "Romantik"], en: ["Drama", "Romance"] },
    director: "Gaspar Noé",
    cast: ["Karl Glusman", "Aomi Muyock", "Klara Kristin"],
    voteAverage: 6.0,
  },
];

export function getDemoFilms(locale: Locale): Film[] {
  return DEMO_FILMS_RAW.map((f) => ({
    ...f,
    overview: f.overview[locale],
    genres: f.genres[locale],
  }));
}

// İki film için örnek analiz — belgedeki "Örnek film sayfası" bölümünün canlı hâli.
// DİKKAT: Bu veriler ürünün nasıl görüneceğini göstermek için yazılmış TEMSİLÎ
// örneklerdir, gerçek film analizleri DEĞİLDİR. Gerçek sistemde bu veriler
// Python analiz programının Supabase'e yazdığı content_events tablosundan gelecek.
export const DEMO_ANALYSES: Record<number, FilmAnalysis> = {
  597: {
    tmdbId: 597,
    status: "completed",
    subtitleLanguage: "en",
    subtitleVersion: "WEB-DL",
    referenceRuntimeMinutes: 194,
    events: [
      {
        id: "597-1",
        tmdbId: 597,
        category: "sexual_implication",
        startSeconds: 4980,
        endSeconds: 5010,
        severity: 1,
        confidence: 0.74,
        description: {
          tr: "Çizim sahnesi öncesinde imalı bir konuşma geçiyor.",
          en: "A suggestive conversation precedes the drawing scene.",
        },
        source: "subtitle_auto",
        verificationCount: 0,
      },
      {
        id: "597-2",
        tmdbId: 597,
        category: "explicit_sexual_content",
        startSeconds: 5100,
        endSeconds: 5260,
        severity: 2,
        confidence: null,
        description: {
          tr: "Çıplaklık içeren çizim sahnesi (müstehcen olmayan çekim).",
          en: "Drawing scene with nudity (non-explicit framing).",
        },
        source: "community_verified",
        verificationCount: 12,
      },
      {
        id: "597-3",
        tmdbId: 597,
        category: "long_kiss",
        startSeconds: 5820,
        endSeconds: 5845,
        severity: 2,
        confidence: null,
        description: {
          tr: "Araba sahnesi öncesi uzun öpüşme.",
          en: "Long kiss before the car scene.",
        },
        source: "user_contribution",
        verificationCount: 5,
      },
      {
        id: "597-4",
        tmdbId: 597,
        category: "sexual_implication",
        startSeconds: 5900,
        endSeconds: 5960,
        severity: 3,
        confidence: null,
        description: {
          tr: "Araba sahnesi — cinsel birliktelik ima ediliyor, açık görüntü yok.",
          en: "Car scene — sexual encounter implied, nothing shown explicitly.",
        },
        source: "community_verified",
        verificationCount: 9,
      },
      {
        id: "597-5",
        tmdbId: 597,
        category: "short_kiss",
        startSeconds: 8710,
        endSeconds: 8716,
        severity: 1,
        confidence: null,
        description: {
          tr: "Güvertede kısa öpüşme.",
          en: "Brief kiss on the deck.",
        },
        source: "user_contribution",
        verificationCount: 2,
      },
      {
        id: "597-6",
        tmdbId: 597,
        category: "profanity",
        startSeconds: 6543,
        endSeconds: 6545,
        severity: 1,
        confidence: 0.93,
        description: {
          tr: "Kaçış sahnesinde tek küfür kullanımı.",
          en: "Single profanity during the escape scene.",
        },
        source: "subtitle_auto",
        verificationCount: 0,
      },
      {
        id: "597-7",
        tmdbId: 597,
        category: "profanity",
        startSeconds: 9105,
        endSeconds: 9107,
        severity: 1,
        confidence: 0.88,
        description: {
          tr: "Panik anında argo ifade.",
          en: "Slang expression in a moment of panic.",
        },
        source: "subtitle_auto",
        verificationCount: 0,
      },
    ],
  },
  313369: {
    tmdbId: 313369,
    status: "completed",
    subtitleLanguage: "en",
    subtitleVersion: "Blu-ray",
    referenceRuntimeMinutes: 128,
    events: [
      {
        id: "313369-1",
        tmdbId: 313369,
        category: "short_kiss",
        startSeconds: 3480,
        endSeconds: 3486,
        severity: 1,
        confidence: null,
        description: {
          tr: "Gözlemevi sahnesinde kısa öpüşme.",
          en: "Brief kiss in the observatory scene.",
        },
        source: "community_verified",
        verificationCount: 8,
      },
      {
        id: "313369-2",
        tmdbId: 313369,
        category: "long_kiss",
        startSeconds: 5150,
        endSeconds: 5170,
        severity: 2,
        confidence: null,
        description: {
          tr: "Ev sahnesinde uzun öpüşme.",
          en: "Long kiss in the apartment scene.",
        },
        source: "user_contribution",
        verificationCount: 3,
      },
      {
        id: "313369-3",
        tmdbId: 313369,
        category: "profanity",
        startSeconds: 2210,
        endSeconds: 2212,
        severity: 1,
        confidence: 0.9,
        description: {
          tr: "Tartışma sırasında hafif küfür.",
          en: "Mild profanity during an argument.",
        },
        source: "subtitle_auto",
        verificationCount: 0,
      },
      {
        id: "313369-4",
        tmdbId: 313369,
        category: "profanity",
        startSeconds: 4890,
        endSeconds: 4892,
        severity: 2,
        confidence: 0.95,
        description: {
          tr: "Akşam yemeği tartışmasında küfür.",
          en: "Profanity during the dinner argument.",
        },
        source: "subtitle_auto",
        verificationCount: 0,
      },
      {
        id: "313369-5",
        tmdbId: 313369,
        category: "sexual_implication",
        startSeconds: 5120,
        endSeconds: 5140,
        severity: 1,
        confidence: 0.71,
        description: {
          tr: "Geceyi birlikte geçirmeye yönelik ima içeren konuşma.",
          en: "Conversation implying spending the night together.",
        },
        source: "subtitle_auto",
        verificationCount: 0,
      },
    ],
  },
  292431: {
    tmdbId: 292431,
    status: "completed",
    subtitleLanguage: "en",
    subtitleVersion: "Blu-ray",
    referenceRuntimeMinutes: 135,
    events: [
      {
        id: "292431-1",
        tmdbId: 292431,
        category: "explicit_sexual_content",
        startSeconds: 120,
        endSeconds: 510,
        severity: 3,
        confidence: null,
        description: {
          tr: "Açılış sahnesi — uzun ve tamamen açık cinsel içerik.",
          en: "Opening scene — long, fully explicit sexual content.",
        },
        source: "community_verified",
        verificationCount: 24,
      },
      {
        id: "292431-2",
        tmdbId: 292431,
        category: "sexual_dialogue",
        startSeconds: 940,
        endSeconds: 1005,
        severity: 3,
        confidence: 0.96,
        description: {
          tr: "Açık cinsel içerikli uzun konuşma.",
          en: "Long, sexually explicit conversation.",
        },
        source: "subtitle_auto",
        verificationCount: 0,
      },
      {
        id: "292431-3",
        tmdbId: 292431,
        category: "explicit_sexual_content",
        startSeconds: 2470,
        endSeconds: 2820,
        severity: 3,
        confidence: null,
        description: {
          tr: "Uzun ve açık cinsel sahne, yoğun çıplaklık.",
          en: "Long explicit sexual scene with extensive nudity.",
        },
        source: "moderator_verified",
        verificationCount: 15,
      },
      {
        id: "292431-4",
        tmdbId: 292431,
        category: "profanity",
        startSeconds: 3610,
        endSeconds: 3615,
        severity: 2,
        confidence: 0.94,
        description: {
          tr: "Tartışma sahnesinde art arda küfür.",
          en: "Repeated profanity during an argument.",
        },
        source: "subtitle_auto",
        verificationCount: 0,
      },
      {
        id: "292431-5",
        tmdbId: 292431,
        category: "explicit_sexual_content",
        startSeconds: 4950,
        endSeconds: 5410,
        severity: 3,
        confidence: null,
        description: {
          tr: "Bir başka uzun ve açık cinsel sahne.",
          en: "Another long, explicit sexual scene.",
        },
        source: "community_verified",
        verificationCount: 19,
      },
      {
        id: "292431-6",
        tmdbId: 292431,
        category: "sexual_implication",
        startSeconds: 6200,
        endSeconds: 6260,
        severity: 2,
        confidence: 0.82,
        description: {
          tr: "Üçlü ilişkiye yönelik açık ima içeren konuşma.",
          en: "Conversation with overt implication of a threesome.",
        },
        source: "subtitle_auto",
        verificationCount: 0,
      },
    ],
  },
};
